- name: Postgresql PVC
  k8s_v1_persistent_volume_claim:
    name: postgresql-data
    namespace: "{{ namespace }}"
    labels:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    access_modes:
      - ReadWriteMany
    resources_requests:
      storage: '{{ POSTGRES_STORAGE_SIZE }}Gi'
    state: present

- name: create postgres deployment config
  openshift_v1_deployment_config:
    name: postgres
    namespace: '{{ namespace }}'
    labels:
      app: postgres
      service: aerogear-app-metrics
    replicas: 1
    selector:
      app: postgres
      service: aerogear-app-metrics
    spec_template_metadata_labels:
      app: postgres
      service: aerogear-app-metrics
    containers:
    - name: postgresql
      image: "{{ postgres_image }}:{{ postgres_version }}"
      imagePullPolicy: IfNotPresent
      ports:
        - container_port: "{{ postgres_port }}"
      env:
      - name: POSTGRESQL_PASSWORD
        value: "{{ postgres_password }}"
      - name: POSTGRESQL_USER
        value: "{{ postgres_user }}"
      - name: POSTGRESQL_DATABASE
        value: aerogear_mobile_metrics
      volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgresql-data
    volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data

- name: Create db internal service
  k8s_v1_service:
    name: postgres-internal
    namespace: '{{ namespace }}'
    labels:
      app: postgres
      service: aerogear-app-metrics
    selector:
      app: postgres
      service: aerogear-app-metrics
    ports:
      - name: postgres
        port: "{{ postgres_port }}"
        target_port: "{{ postgres_port }}"

- name: Create api server deployment config
  openshift_v1_deployment_config:
    name: aerogear-app-metrics
    namespace: '{{ namespace }}'
    labels:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    replicas: 1
    selector:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    spec_template_metadata_labels:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    containers:
    - name: aerogear-app-metrics
      image: '{{ api_server_image }}:{{ api_server_version }}'
      imagePullPolicy: IfNotPresent
      env:
      - name: PGHOST
        value: postgres-internal
      - name: PGPASSWORD
        value: "{{ postgres_password}}"
      - name: PGUSER
        value: "{{ postgres_user}}"
      - name: PGDATABASE
        value: aerogear_mobile_metrics

- name: Create api server service
  k8s_v1_service:
    name: aerogear-app-metrics
    namespace: '{{ namespace }}'
    labels:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    selector:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    ports:
      - name: web
        port: 443
        target_port: '{{ api_server_port }}'

- name: Create api server route
  openshift_v1_route:
    name: aerogear-app-metrics
    namespace: '{{ namespace }}'
    labels:
      app: aerogear-app-metrics
      service: aerogear-app-metrics
    to_name: aerogear-app-metrics
    spec_port_target_port: web
