prometheus_image: "registry.access.redhat.com/openshift3/prometheus"
prometheus_version: "latest"
prometheus_port: 9090
prometheus_proxy_port: 4180
# Grafana values
grafana_image: "docker.io/grafana/grafana"
# TODO: Change to 4.7.0 when a tag is available
grafana_version: "master"
grafana_port: 3000
grafana_proxy_port: 4181
grafana_log_level: info
# OAuth Proxy values
proxy_image: "docker.io/openshift/oauth-proxy"
proxy_version: "v1.1.0"
