# Prometheus Values
prometheus_image: "registry.access.redhat.com/openshift3/prometheus"
prometheus_version: "latest"
prometheus_port: 9090
prometheus_proxy_port: 4180

# Grafana values
grafana_image: "docker.io/aerogearcatalog/grafana"
grafana_version: "latest"
grafana_port: 3000
grafana_proxy_port: 4181
grafana_log_level: debug

# App Metrics values
api_server_image: "docker.io/steventobin/aerogear-metrics-api"
api_server_version: "latest"

# OAuth Proxy values
proxy_image: "docker.io/openshift/oauth-proxy"
proxy_version: "v1.1.0"
