- openshift_v1_route:
    name: prometheus
    namespace: '{{ namespace }}'
    state: absent


- k8s_v1_service:
    name: prometheus
    namespace: '{{ namespace }}'
    state: absent


- openshift_v1_deployment_config:
    name: prometheus
    namespace: '{{ namespace }}'
    state: absent

- name: Delete Prometheus config-map
  shell: oc delete configmap prometheus-configmap -n '{{ namespace }}'
