---
- name: Test metrics-apb
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no

  post_tasks:
  - name: Load default variables for testing
    include_vars: test_defaults.yml
  - name: create project for namespace
    openshift_v1_project:
      name: '{{ namespace }}'
  - name: Run the provision role.
    include_role:
      name: provision-metrics-apb
  - name: Run the test role.
    include_role:
      name: test-metrics-apb